
#ifndef _RENDERINGPASSDEFS_H_
#define _RENDERINGPASSDEFS_H_

#define RENDERINGPASS_SHADOWS					-1
#define RENDERINGPASS_AMBIENT					0
#define RENDERINGPASS_SUN						1
#define RENDERINGPASS_LIGHT						2
#define RENDERINGPASS_SPECIAL					3

#define RENDERINGPASS_COUNT						4

#endif